# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profq', '0002_auto_20171013_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='user_id',
            new_name='bet_maker',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_taker',
            field=models.CharField(default='loser', max_length=200),
        ),
    ]
