# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profq', '0003_auto_20171013_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
