# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profq', '0004_auto_20171013_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_maker',
            field=models.CharField(default='maker', max_length=200),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_taker',
            field=models.CharField(default='taker', max_length=200),
        ),
    ]
